---
- name: Install docker in Manjaro
  include_role:
    name: geerlingguy.docker

- name: Install all packages that we will need in our system
  tags: packages
  block:
    - name: Upgrade all packages
      community.general.pacman:
        update_cache: true
        upgrade: true

    - name: Install YAY in our system
      community.general.pacman:
        name: yay
        state: present
      when: ansible_pkg_mgr == 'pacman'

    - name: Install packages that we have in the list
      command: yay -Sy --noconfirm {{ item.packages | join(' ') }}
      when: item.state == 'present' and item.packages.0 is defined
      with_items: "{{ package_list }}"
      become: false

    - name: Remove packages that we have in the list
      command: yay -R --noconfirm {{ item.packages | join(' ') }}
      when: item.state == 'absent' and item.packages.0 is defined
      with_items: "{{ package_list }}"
      become: false

- name: Setting all the things to Microk8s start automatically
  tags: microk8s
  block:
    - name: Ensure that Cluster Agent service is enabled and running
      service:
        name: snap.microk8s.daemon-cluster-agent.service
        enabled: yes
        daemon_reload: yes
        state: started
      when: ansible_check_mode == false

    - name: Ensure that Containerd service is enabled and running
      service:
        name: snap.microk8s.daemon-containerd.service
        enabled: yes
        daemon_reload: yes
        state: started
      when: ansible_check_mode == false

    - name: Ensure that K8-Dqlite service is enabled and running
      service:
        name: snap.microk8s.daemon-k8s-dqlite.service
        enabled: yes
        daemon_reload: yes
        state: started
      when: ansible_check_mode == false

    - name: Ensure that Kubelite service is enabled and running
      service:
        name: snap.microk8s.daemon-kubelite.service
        enabled: yes
        daemon_reload: yes
        state: started
      when: ansible_check_mode == false

    - name: Ensure that ApiServer-Kicker service is enabled and running
      service:
        name: snap.microk8s.daemon-apiserver-kicker.service
        enabled: yes
        daemon_reload: yes
        state: started
      when: ansible_check_mode == false
   
# All tasks for RedHad family SO
- name: Changing the size max of files that were can handle for Visual Studio Code
  lineinfile:
    path: /etc/sysctl.conf
    regexp: 'fs.inotify.max_user_watches='
    line: fs.inotify.max_user_watches=524288
    create: yes
  become: true
